package com.nair.aclservice.constants;

public abstract class Queries {

	public static final String SELECT_USER_BY_ID = "SELECT USER_ID, USER_NAME FROM USERS WHERE USER_ID = ? AND STATUS = ?";
	
	public static final String SELECT_USER_BY_NAME = "SELECT USER_ID, USER_NAME FROM USERS WHERE USER_NAME = ? AND STATUS = ?";
	
	public static final String INSERT_USER = "INSERT INTO USERS(USER_NAME, STATUS) VALUES (? , ?)";
	
	public static final String SELECT_RESOURCE_BY_ID = "SELECT RESOURCE_ID, RESOURCE_NAME, RESOURCE_DESCRIPTION FROM RESOURCES WHERE RESOURCE_ID = ? AND STATUS = ?";

	public static final String SELECT_RESOURCE_BY_NAME = "SELECT RESOURCE_ID, RESOURCE_NAME, RESOURCE_DESCRIPTION FROM RESOURCES WHERE RESOURCE_NAME = ? AND STATUS = ?";
	
	public static final String INSERT_RESOURCE = "INSERT INTO RESOURCES(RESOURCE_NAME, RESOURCE_DESCRIPTION, STATUS) VALUES (? , ? , ?)";
	
	public static final String SELECT_ROLE_BY_ID = "SELECT ROLE_ID, ROLE_NAME FROM ROLES WHERE ROLE_ID = ? AND STATUS = ?";
	
	public static final String SELECT_ROLE_BY_NAME = "SELECT ROLE_ID, ROLE_NAME FROM ROLES WHERE ROLE_NAME = ? AND STATUS = ?";
	
	public static final String INSERT_ROLE = "INSERT INTO ROLES(ROLE_NAME, STATUS) VALUES(? , ?)";
	
	public static final String MAP_USER_ROLE = "INSERT INTO USER_ROLE_MAPPING(USER_ID, ROLE_ID, STATUS) VALUES( ? , ? , ? )";
	
	public static final String DELETE_USER_ROLE_MAPPING = "DELETE FROM USER_ROLE_MAPPING WHERE USER_ID = ? AND ROLE_ID = ?";
	
	public static final String DELETE_ROLE = "DELETE FROM ROLES WHERE ROLE_ID = ?";
	
	public static final String DELETE_ROLE_MAPPING = "DELETE FROM USER_ROLE_MAPPING WHERE ROLE_ID = ?";
	
	public static final String DELETE_ROLE_PERMISSIONS = "DELETE FROM PERMISSIONS WHERE ROLE_ID = ?";
	
	public static final String ADD_PERMISSIONS = "INSERT INTO PERMISSIONS(ROLE_ID , ACCESS_LEVEL, RESOURCE_ID, STATUS ) VALUES(? , ? , ?, ?)";
	
	public static final String CHECK_PERMISSIONS = "SELECT PERMISSION_ID FROM PERMISSIONS WHERE ROLE_ID = ? AND RESOURCE_ID = ? AND ACCESS_LEVEL = ? AND STATUS = ?";

	public static final String DELETE_PERMISSION = "DELETE FROM PERMISSIONS WHERE ROLE_ID = ? AND RESOURCE_ID = ? AND ACCESS_LEVEL = ? AND STATUS = ?";
	
	public static final String GET_USER_ROLES = "SELECT ROLE_ID FROM USER_ROLE_MAPPING WHERE USER_ID = ? AND STATUS = ?";
}
